backend:
  name: git-gateway
  branch: master

# publish_mode: editorial_workflow
media_folder: src/images
public_folder: ''

collections:
  - name: content
    label: Content
    files:
      - label: 'Answers'
        name: 'answers'
        file: 'src/answers.json'
        fields:
          - label: 'COPYWRITER'
            name: 'copywriter'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Answers
                name: answers
                widget: list
                fields:
                  - { label: Icon, name: icon, widget: image }
                  - { label: Alt Text, name: alt, widget: string }
                  - { label: Title, name: title, widget: string }
                  - { label: Banner Text, name: banner, widget: string }
              - { label: Banner Background, name: bannerBG, widget: image }
          - label: 'ART DIRECTOR DESIGNER'
            name: 'ad'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Answers
                name: answers
                widget: list
                fields:
                  - { label: Icon, name: icon, widget: image }
                  - { label: Alt Text, name: alt, widget: string }
                  - { label: Title, name: title, widget: string }
                  - { label: Banner Text, name: banner, widget: string }
              - { label: Banner Background, name: bannerBG, widget: image }
          - label: 'ACCOUNT MANAGER'
            name: 'am'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Answers
                name: answers
                widget: list
                fields:
                  - { label: Icon, name: icon, widget: image }
                  - { label: Alt Text, name: alt, widget: string }
                  - { label: Title, name: title, widget: string }
                  - { label: Banner Text, name: banner, widget: string }
              - { label: Banner Background, name: bannerBG, widget: image }
          - label: 'CREATIVE DIRECTOR'
            name: 'cd'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Answers
                name: answers
                widget: list
                fields:
                  - { label: Icon, name: icon, widget: image }
                  - { label: Alt Text, name: alt, widget: string }
                  - { label: Title, name: title, widget: string }
                  - { label: Banner Text, name: banner, widget: string }
              - { label: Banner Background, name: bannerBG, widget: image }
          - label: 'PRODUCER'
            name: 'producer'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Answers
                name: answers
                widget: list
                fields:
                  - { label: Icon, name: icon, widget: image }
                  - { label: Alt Text, name: alt, widget: string }
                  - { label: Title, name: title, widget: string }
                  - { label: Banner Text, name: banner, widget: string }
              - { label: Banner Background, name: bannerBG, widget: image }
          - label: 'DEFAULT'
            name: 'default'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Answers
                name: answers
                widget: list
                fields:
                  - { label: Icon, name: icon, widget: image }
                  - { label: Alt Text, name: alt, widget: string }
                  - { label: Banner Text, name: banner, widget: string }
              - { label: Banner Background, name: bannerBG, widget: image }
